CREATE TABLE users (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
username VARCHAR(50) UNIQUE NOT NULL,
email VARCHAR(100) UNIQUE NOT NULL,
CREATE DATABASE IF NOT EXISTS punkpad;
USE punkpad;

password VARCHAR(255) NOT NULL,
role VARCHAR(50),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE genres (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE sub_genres (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(50) NOT NULL,
genre_id BIGINT NOT NULL,
FOREIGN KEY (genre_id) REFERENCES genres(id)
);

CREATE TABLE chord_progresssions (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(100) NOT NULL,
user_id BIGINT NOT NULL,
tempo INT,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREGIN KEY(user_id) REFERENCES users(id),
FOREIGN KEY (sub_genre_id) REFERENCES sub_genres(id)
);

CREATE TABLE chords (
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(10) NOT NULL,
position_index INT NOT NULL,
FOREIGN KEY (progression_id) REFERENCES chord_progressions(id) ON DELETE CASCADE
);


